// <auto-generated />
using System;
using Ambiquality.Evidence.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Ambiquality.Evidence.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EvidenceDbContext))]
    [Migration("20260520124000_0003_RoomAggregate")]
    partial class _0003_RoomAggregate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Buildings.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnonymizationLevel")
                        .HasColumnType("uuid")
                        .HasColumnName("anonymization_level");

                    b.Property<string>("BuildingTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("building_type_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("buildings", "evidence");
                });

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("UriSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uri_slug");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId", "UriSlug")
                        .IsUnique()
                        .HasDatabaseName("IX_room_building_uri_slug_unique");

                    b.HasOne("Ambiquality.Evidence.Api.Domain.Buildings.Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_rooms_buildings_building_id");

                    b.ToTable("rooms", "evidence");

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomBuildingHistory", "BuildingHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("BuildingId")
                                .HasColumnType("uuid")
                                .HasColumnName("building_id");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .IsRequired()
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_building_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("FK_room_building_history_rooms_room_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomExposureHistory", "ExposureHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("ExposureCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("exposure_code");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .IsRequired()
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_exposure_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("FK_room_exposure_history_rooms_room_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomFloorHistory", "FloorHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<byte>("Floor")
                                .HasColumnType("smallint")
                                .HasColumnName("floor");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .IsRequired()
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_floor_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("FK_room_floor_history_rooms_room_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomFunctionHistory", "FunctionHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("FunctionCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("function_code");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .IsRequired()
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_function_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("FK_room_function_history_rooms_room_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomGeometryHistory", "GeometryHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<decimal>("AreaM2")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric")
                                .HasColumnName("area_m2");

                            b1.Property<decimal>("CeilingHeightM")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric")
                                .HasColumnName("ceiling_height_m");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .IsRequired()
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_geometry_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("FK_room_geometry_history_rooms_room_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomNameHistory", "NameHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("name");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .IsRequired()
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_name_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("FK_room_name_history_rooms_room_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomPollutionSourceHistory", "PollutionSourceHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<string>("SourceCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_code");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .IsRequired()
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_pollution_source_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("FK_room_pollution_source_history_rooms_room_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomVentilationHistory", "VentilationHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<string>("VentilationType")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ventilation_type");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .IsRequired()
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_ventilation_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("FK_room_ventilation_history_rooms_room_id");
                        });
                });

#pragma warning restore 612, 618
        }
    }
}
