// <auto-generated />
using System;
using Ambiquality.Evidence.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Ambiquality.Evidence.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EvidenceDbContext))]
    [Migration("20260519165216_FixCompositeKeys")]
    partial class FixCompositeKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("evidence")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Buildings.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("UriSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uri_slug");

                    b.HasKey("Id");

                    b.HasIndex("UriSlug")
                        .IsUnique();

                    b.ToTable("buildings", "evidence");
                });

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Buildings.Building", b =>
                {
                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Buildings.BuildingAddressHistory", "AddressHistory", b1 =>
                        {
                            b1.Property<Guid>("building_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("building_id", "RecordedAt");

                            b1.ToTable("building_address_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("building_id");

                            b1.OwnsOne("Ambiquality.Evidence.Api.Domain.Buildings.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("BuildingAddressHistorybuilding_id")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("BuildingAddressHistoryRecordedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("city");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)")
                                        .HasColumnName("country");

                                    b2.Property<string>("Postcode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("postcode");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("street");

                                    b2.HasKey("BuildingAddressHistorybuilding_id", "BuildingAddressHistoryRecordedAt");

                                    b2.ToTable("building_address_history", "evidence");

                                    b2.WithOwner()
                                        .HasForeignKey("BuildingAddressHistorybuilding_id", "BuildingAddressHistoryRecordedAt");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Buildings.BuildingLocationHistory", "LocationHistory", b1 =>
                        {
                            b1.Property<Guid>("building_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("Anonymization")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("anonymization");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("building_id", "RecordedAt");

                            b1.ToTable("building_location_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("building_id");

                            b1.OwnsOne("Ambiquality.Evidence.Api.Domain.Buildings.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("BuildingLocationHistorybuilding_id")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("BuildingLocationHistoryRecordedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<double>("Latitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("double precision")
                                        .HasColumnName("latitude");

                                    b2.Property<double>("Longitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("double precision")
                                        .HasColumnName("longitude");

                                    b2.HasKey("BuildingLocationHistorybuilding_id", "BuildingLocationHistoryRecordedAt");

                                    b2.ToTable("building_location_history", "evidence");

                                    b2.WithOwner()
                                        .HasForeignKey("BuildingLocationHistorybuilding_id", "BuildingLocationHistoryRecordedAt");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Buildings.BuildingNameHistory", "NameHistory", b1 =>
                        {
                            b1.Property<Guid>("building_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("name");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("building_id", "RecordedAt");

                            b1.ToTable("building_name_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("building_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Buildings.BuildingTypeHistory", "TypeHistory", b1 =>
                        {
                            b1.Property<Guid>("building_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("BuildingTypeCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("building_type_code");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("building_id", "RecordedAt");

                            b1.ToTable("building_type_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("building_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Buildings.BuildingYearsHistory", "YearsHistory", b1 =>
                        {
                            b1.Property<Guid>("building_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.Property<short?>("YearBuilt")
                                .HasColumnType("smallint")
                                .HasColumnName("year_built");

                            b1.Property<short?>("YearRenovated")
                                .HasColumnType("smallint")
                                .HasColumnName("year_renovated");

                            b1.HasKey("building_id", "RecordedAt");

                            b1.ToTable("building_years_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("building_id");
                        });

                    b.Navigation("AddressHistory");

                    b.Navigation("LocationHistory");

                    b.Navigation("NameHistory");

                    b.Navigation("TypeHistory");

                    b.Navigation("YearsHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
