// <auto-generated />
using System;
using Ambiquality.Evidence.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Ambiquality.Evidence.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EvidenceDbContext))]
    [Migration("20260608122452_0010_OfnCzechAddress")]
    partial class _0010_OfnCzechAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("evidence")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Buildings.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("UriSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uri_slug");

                    b.HasKey("Id");

                    b.HasIndex("UriSlug")
                        .IsUnique();

                    b.ToTable("buildings", "evidence");
                });

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("UriSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uri_slug");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("UriSlug")
                        .IsUnique()
                        .HasDatabaseName("IX_room_uri_slug_unique");

                    b.ToTable("rooms", "evidence");
                });

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Sensors.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_key_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CurrentBuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_building_id");

                    b.Property<Guid>("CurrentRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_room_id");

                    b.Property<string>("UriSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uri_slug");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRoomId");

                    b.HasIndex("UriSlug")
                        .IsUnique()
                        .HasDatabaseName("IX_sensor_uri_slug_unique");

                    b.ToTable("sensors", "evidence");
                });

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Users.UserProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_user_projections_auth_user_id_unique");

                    b.ToTable("user_projections", "evidence");
                });

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Buildings.Building", b =>
                {
                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Buildings.BuildingAddressHistory", "AddressHistory", b1 =>
                        {
                            b1.Property<Guid>("building_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("building_id", "RecordedAt");

                            b1.ToTable("building_address_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("building_id");

                            b1.OwnsOne("Ambiquality.Evidence.Api.Domain.Buildings.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("BuildingAddressHistorybuilding_id")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("BuildingAddressHistoryRecordedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<long>("AddressPointCode")
                                        .HasColumnType("bigint")
                                        .HasColumnName("address_point_code");

                                    b2.Property<string>("DistrictName")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("district_name");

                                    b2.Property<int>("HouseNumber")
                                        .HasColumnType("integer")
                                        .HasColumnName("house_number");

                                    b2.Property<string>("HouseNumberType")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("house_number_type");

                                    b2.Property<string>("MunicipalityName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("municipality_name");

                                    b2.Property<string>("MunicipalityPartName")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("municipality_part_name");

                                    b2.Property<int?>("OrientationNumber")
                                        .HasColumnType("integer")
                                        .HasColumnName("orientation_number");

                                    b2.Property<string>("OrientationNumberLetter")
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)")
                                        .HasColumnName("orientation_number_letter");

                                    b2.Property<string>("Psc")
                                        .IsRequired()
                                        .HasMaxLength(5)
                                        .HasColumnType("character varying(5)")
                                        .HasColumnName("psc");

                                    b2.Property<string>("RegionName")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("region_name");

                                    b2.Property<string>("StreetName")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("street_name");

                                    b2.HasKey("BuildingAddressHistorybuilding_id", "BuildingAddressHistoryRecordedAt");

                                    b2.ToTable("building_address_history", "evidence");

                                    b2.WithOwner()
                                        .HasForeignKey("BuildingAddressHistorybuilding_id", "BuildingAddressHistoryRecordedAt");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Buildings.BuildingLocationHistory", "LocationHistory", b1 =>
                        {
                            b1.Property<Guid>("building_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("building_id", "RecordedAt");

                            b1.ToTable("building_location_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("building_id");

                            b1.OwnsOne("Ambiquality.Evidence.Api.Domain.Buildings.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("BuildingLocationHistorybuilding_id")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("BuildingLocationHistoryRecordedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<double>("Latitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("double precision")
                                        .HasColumnName("latitude");

                                    b2.Property<double>("Longitude")
                                        .HasPrecision(9, 6)
                                        .HasColumnType("double precision")
                                        .HasColumnName("longitude");

                                    b2.HasKey("BuildingLocationHistorybuilding_id", "BuildingLocationHistoryRecordedAt");

                                    b2.ToTable("building_location_history", "evidence");

                                    b2.WithOwner()
                                        .HasForeignKey("BuildingLocationHistorybuilding_id", "BuildingLocationHistoryRecordedAt");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Buildings.BuildingNameHistory", "NameHistory", b1 =>
                        {
                            b1.Property<Guid>("building_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("name");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("building_id", "RecordedAt");

                            b1.ToTable("building_name_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("building_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Buildings.BuildingTypeHistory", "TypeHistory", b1 =>
                        {
                            b1.Property<Guid>("building_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("BuildingTypeCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("building_type_code");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("building_id", "RecordedAt");

                            b1.ToTable("building_type_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("building_id");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Buildings.BuildingYearsHistory", "YearsHistory", b1 =>
                        {
                            b1.Property<Guid>("building_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.Property<short?>("YearBuilt")
                                .HasColumnType("smallint")
                                .HasColumnName("year_built");

                            b1.Property<short?>("YearRenovated")
                                .HasColumnType("smallint")
                                .HasColumnName("year_renovated");

                            b1.HasKey("building_id", "RecordedAt");

                            b1.ToTable("building_years_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("building_id");
                        });

                    b.Navigation("AddressHistory");

                    b.Navigation("LocationHistory");

                    b.Navigation("NameHistory");

                    b.Navigation("TypeHistory");

                    b.Navigation("YearsHistory");
                });

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Rooms.Room", b =>
                {
                    b.HasOne("Ambiquality.Evidence.Api.Domain.Buildings.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomExposureHistory", "ExposureHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("ExposureCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("exposure_code");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_exposure_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomFloorHistory", "FloorHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<byte>("Floor")
                                .HasColumnType("smallint")
                                .HasColumnName("floor");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_floor_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomFunctionHistory", "FunctionHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("FunctionCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("function_code");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_function_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomGeometryHistory", "GeometryHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<double?>("AreaM2")
                                .HasPrecision(10, 2)
                                .HasColumnType("double precision")
                                .HasColumnName("area_m2");

                            b1.Property<double?>("CeilingHeightM")
                                .HasPrecision(5, 2)
                                .HasColumnType("double precision")
                                .HasColumnName("ceiling_height_m");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_geometry_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomNameHistory", "NameHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("name");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_name_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomPollutionSourceHistory", "PollutionSourceHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<string>("SourceCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("source_code");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_pollution_source_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Rooms.RoomVentilationHistory", "VentilationHistory", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.Property<string>("VentilationType")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ventilation_type");

                            b1.HasKey("RoomId", "RecordedAt");

                            b1.ToTable("room_ventilation_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("ExposureHistory");

                    b.Navigation("FloorHistory");

                    b.Navigation("FunctionHistory");

                    b.Navigation("GeometryHistory");

                    b.Navigation("NameHistory");

                    b.Navigation("PollutionSourceHistory");

                    b.Navigation("VentilationHistory");
                });

            modelBuilder.Entity("Ambiquality.Evidence.Api.Domain.Sensors.Sensor", b =>
                {
                    b.HasOne("Ambiquality.Evidence.Api.Domain.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("CurrentRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Sensors.SensorIdentityHistory", "IdentityHistory", b1 =>
                        {
                            b1.Property<Guid>("SensorId")
                                .HasColumnType("uuid")
                                .HasColumnName("sensor_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("Manufacturer")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("manufacturer");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("model");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<string>("SerialNumber")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("serial_number");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("SensorId", "RecordedAt");

                            b1.ToTable("sensor_identity_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("SensorId");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Sensors.SensorMeasuredParameterHistory", "MeasuredParameterHistory", b1 =>
                        {
                            b1.Property<Guid>("SensorId")
                                .HasColumnType("uuid")
                                .HasColumnName("sensor_id");

                            b1.Property<string>("ParameterCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("parameter_code");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("SensorId", "ParameterCode", "RecordedAt");

                            b1.ToTable("sensor_measured_parameter_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("SensorId");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Sensors.SensorPlacementHistory", "PlacementHistory", b1 =>
                        {
                            b1.Property<Guid>("SensorId")
                                .HasColumnType("uuid")
                                .HasColumnName("sensor_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("BuildingId")
                                .HasColumnType("uuid")
                                .HasColumnName("building_id");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("room_id");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("SensorId", "RecordedAt");

                            b1.ToTable("sensor_placement_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("SensorId");
                        });

                    b.OwnsMany("Ambiquality.Evidence.Api.Domain.Sensors.SensorStatusHistory", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("SensorId")
                                .HasColumnType("uuid")
                                .HasColumnName("sensor_id");

                            b1.Property<DateTime>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<Guid>("RecordedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recorded_by");

                            b1.Property<string>("StatusCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("status_code");

                            b1.Property<NpgsqlRange<DateTime>>("Validity")
                                .HasColumnType("tstzrange")
                                .HasColumnName("validity");

                            b1.HasKey("SensorId", "RecordedAt");

                            b1.ToTable("sensor_status_history", "evidence");

                            b1.WithOwner()
                                .HasForeignKey("SensorId");
                        });

                    b.Navigation("IdentityHistory");

                    b.Navigation("MeasuredParameterHistory");

                    b.Navigation("PlacementHistory");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
