// <auto-generated />
using System;
using Ambiquality.Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ambiquality.Ingestion.Api.Migrations
{
    [DbContext(typeof(IeqDbContext))]
    [Migration("20260601140730_AddMeasurementExports")]
    partial class AddMeasurementExports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ieq")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambiquality.Core.Domain.Measurements.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<string>("InvalidatedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("invalidated_reason");

                    b.Property<bool>("IsInvalid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_invalid");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("observed_at");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter_code");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id", "ReceivedAt");

                    b.HasIndex("SensorId", "ParameterCode", "ReceivedAt")
                        .HasDatabaseName("IX_measurements_sensor_parameter_time");

                    b.ToTable("measurements", "ieq");
                });

            modelBuilder.Entity("Ambiquality.Core.Domain.Measurements.MeasurementExport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompressFormat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("compress_format");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("download_url");

                    b.Property<DateTimeOffset>("ExportedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("exported_at");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_key");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("media_type");

                    b.Property<short>("Month")
                        .HasColumnType("smallint")
                        .HasColumnName("month");

                    b.Property<long?>("RecordCount")
                        .HasColumnType("bigint")
                        .HasColumnName("record_count");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month", "MediaType")
                        .IsUnique()
                        .HasDatabaseName("IX_measurement_exports_year_month_media_type");

                    b.ToTable("measurement_exports", "ieq");
                });

            modelBuilder.Entity("Ambiquality.Core.Domain.Measurements.ParameterRange", b =>
                {
                    b.Property<string>("ParameterCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter_code");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("ParameterCode");

                    b.ToTable("parameter_ranges", "ieq");

                    b.HasData(
                        new
                        {
                            ParameterCode = "co2",
                            MaxValue = 50000.0,
                            MinValue = 0.0,
                            Unit = "ppm"
                        },
                        new
                        {
                            ParameterCode = "eco2",
                            MaxValue = 65000.0,
                            MinValue = 0.0,
                            Unit = "ppm"
                        },
                        new
                        {
                            ParameterCode = "co",
                            MaxValue = 2000.0,
                            MinValue = 0.0,
                            Unit = "ppm"
                        },
                        new
                        {
                            ParameterCode = "o3",
                            MaxValue = 500.0,
                            MinValue = 0.0,
                            Unit = "µg/m³"
                        },
                        new
                        {
                            ParameterCode = "no2",
                            MaxValue = 500.0,
                            MinValue = 0.0,
                            Unit = "µg/m³"
                        },
                        new
                        {
                            ParameterCode = "so2",
                            MaxValue = 500.0,
                            MinValue = 0.0,
                            Unit = "µg/m³"
                        },
                        new
                        {
                            ParameterCode = "voc",
                            MaxValue = 60000.0,
                            MinValue = 0.0,
                            Unit = "ppb"
                        },
                        new
                        {
                            ParameterCode = "pm1",
                            MaxValue = 500.0,
                            MinValue = 0.0,
                            Unit = "µg/m³"
                        },
                        new
                        {
                            ParameterCode = "pm2_5",
                            MaxValue = 500.0,
                            MinValue = 0.0,
                            Unit = "µg/m³"
                        },
                        new
                        {
                            ParameterCode = "pm4",
                            MaxValue = 1000.0,
                            MinValue = 0.0,
                            Unit = "µg/m³"
                        },
                        new
                        {
                            ParameterCode = "pm10",
                            MaxValue = 1000.0,
                            MinValue = 0.0,
                            Unit = "µg/m³"
                        },
                        new
                        {
                            ParameterCode = "temperature",
                            MaxValue = 85.0,
                            MinValue = -40.0,
                            Unit = "°C"
                        },
                        new
                        {
                            ParameterCode = "humidity",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Unit = "%"
                        },
                        new
                        {
                            ParameterCode = "air_velocity",
                            MaxValue = 10.0,
                            MinValue = 0.0,
                            Unit = "m/s"
                        },
                        new
                        {
                            ParameterCode = "pressure",
                            MaxValue = 110000.0,
                            MinValue = 85000.0,
                            Unit = "Pa"
                        },
                        new
                        {
                            ParameterCode = "illuminance",
                            MaxValue = 100000.0,
                            MinValue = 0.0,
                            Unit = "lx"
                        },
                        new
                        {
                            ParameterCode = "cct",
                            MaxValue = 20000.0,
                            MinValue = 1000.0,
                            Unit = "K"
                        },
                        new
                        {
                            ParameterCode = "laeq",
                            MaxValue = 140.0,
                            MinValue = 0.0,
                            Unit = "dB(A)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
