// <auto-generated />
using System;
using Ambiquality.Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ambiquality.Ingestion.Api.Migrations
{
    [DbContext(typeof(IeqDbContext))]
    partial class IeqDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ieq")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ambiquality.Core.Domain.Measurements.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<string>("InvalidatedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("invalidated_reason");

                    b.Property<bool>("IsInvalid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_invalid");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("observed_at");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter_code");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id", "ReceivedAt");

                    b.HasIndex("SensorId", "ParameterCode", "ReceivedAt")
                        .HasDatabaseName("IX_measurements_sensor_parameter_time");

                    b.ToTable("measurements", "ieq");
                });

            modelBuilder.Entity("Ambiquality.Core.Domain.Measurements.ParameterRange", b =>
                {
                    b.Property<string>("ParameterCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter_code");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("ParameterCode");

                    b.ToTable("parameter_ranges", "ieq");

                    b.HasData(
                        new
                        {
                            ParameterCode = "co2",
                            MaxValue = 50000.0,
                            MinValue = 0.0,
                            Unit = "ppm"
                        },
                        new
                        {
                            ParameterCode = "temperature",
                            MaxValue = 85.0,
                            MinValue = -40.0,
                            Unit = "°C"
                        },
                        new
                        {
                            ParameterCode = "humidity",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Unit = "%"
                        },
                        new
                        {
                            ParameterCode = "pm",
                            MaxValue = 1000.0,
                            MinValue = 0.0,
                            Unit = "µg/m³"
                        },
                        new
                        {
                            ParameterCode = "voc",
                            MaxValue = 60000.0,
                            MinValue = 0.0,
                            Unit = "ppb"
                        },
                        new
                        {
                            ParameterCode = "acoustics",
                            MaxValue = 140.0,
                            MinValue = 0.0,
                            Unit = "dB"
                        },
                        new
                        {
                            ParameterCode = "light",
                            MaxValue = 100000.0,
                            MinValue = 0.0,
                            Unit = "lx"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
